### ISSUE TITLE
Establecer el acta de constitución del proyecto

### ISSUE THREAD

**Issue by a-calero3** [a-calero3/Gestion-de-Inventario-Malibu-Peru#1]
Dejar constancia del Project Charter del Proyecto.

**Comment by Volsknight** [comment]
Project Charter finalizado y establecido. 
Acta de Constitución del Proyecto
https://github.com/a-calero3/Gestion-de-Inventario-Malibu-Peru/blob/a85e4d7a76010a1ffdc2fede021ffd39e9bfc467/docs/Acta%20de%20Constituci%C3%B3n%20del%20Proyecto%20-%20GCM%20G4.pdf 
Project Charter 
https://github.com/a-calero3/Gestion-de-Inventario-Malibu-Peru/blob/a85e4d7a76010a1ffdc2fede021ffd39e9bfc467/docs/Project-Charter-G4.docx.pdf
